# Generated by Django 4.2.2 on 2023-07-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_gallery_image_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ActiveSession',
        ),
    ]
