# Generated by Django 4.2.2 on 2023-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_gallery_active_news_active_delete_activesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='active',
        ),
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
