# Generated by Django 4.2.2 on 2023-08-05 06:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_notice_issue_date_result_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='member',
        ),
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 12, 13, 37, 295121)),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
