# Generated by Django 4.2.2 on 2023-08-05 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_members_member_alter_notice_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 12, 18, 41, 884611)),
        ),
    ]
