# Generated by Django 4.2.2 on 2023-08-27 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_notice_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 27, 17, 4, 13, 984891)),
        ),
    ]
